### ISSUE TITLE
Complx: assertion failed when poking around test results dialog

### ISSUE THREAD

**Issue by lucasec** [TricksterGuy/complx#45] opened 2015-10-09 04:07 UTC
To replicate, run the test XML below on working code.  In the test report dialog, expand the root of the tree, and click the first child (labeled "MC91 (101)").  Error should occur before the frame is rendered.

Test XML:
```xml
<?xml version="1.0"?>
<test-suite>
    <!-- Test case you may have multiple of these --> 
    <test-case> 
        <name>mc91(101)</name>
        <!-- This flag determines if the test has a time limit in number of instructions default is 0 (false). Best practice is to always use this. --> 
        <has-max-executions>1</has-max-executions>
        <!-- The maximum number of instructions to run for.  Only works if the above flag for has-max-executions is 1 (true) --> 
        <max-executions>1000000</max-executions>
        <!-- Randomize memory before the test default is 0 (false)--> 
        <randomize>1</randomize>
        <!-- Specify the inputs to your assembly code here --> 
        <input>
	    <!-- Parameter setting change N to be 101 -->
            <test-value><address>N</address><value>101</value></test-value>
            <!-- Prepare to call subroutine MC91 the following shall happen -->
            <!-- Set the Stack pointer R6 to xF000 -->
            <!-- Set the Return address R7 to x5000, A halt statement shall be placed here as well -->
            <!-- Set the Frame pointer R5 to be some value, after your code is finished running R5 better be the same value. -->
            <!-- Parameters will be loaded in the stack as specified in the calling convention and R6 shall point to the first parameter -->
            <test-subr><name>MC91</name><stack>xF000</stack><r7>x5000</r7><r5>xCAFE</r5><params>MEM[N]</params></test-subr>
        </input>
        <!-- Specify things you want to verify here -->
        <output>
            <!-- Answer is 91, no local variables-->
            <!-- The following checks are made -->
            <!-- R6 should be pointing at xEFFE (initial stack - num_params - 1) -->
            <!-- xEFFE must contain the answer 91 -->
            <!-- PC must be pointing at the return address specified above (x5000) -->
            <!-- R5 must contain the old frame pointer value specified above (xCAFE) -->
            <!-- Parameter 101 must not be modified and should still be located at xEFFF -->
            <!-- Return address x5000 should be located at xEFFD -->
            <!-- Old frame pointer xCAFE should be located at xEFFC -->
            <test-subr>
                <answer>91</answer>
                <!-- No local variables, so not including a locals tag -->
                <!-- Ignore this section unless you are a TA -->
                <points>
                    <answer>1</answer>
                    <params>1</params>
                    <r7>1</r7>
                    <r6>1</r6>
                    <r5>1</r5>
                    <locals>1</locals>
                </points>
                <deductions-per-mistake>1</deductions-per-mistake>
            </test-subr>
        </output>
    </test-case>
</test-suite>
```

Assertion details:
```
ASSERT INFO:
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

BACKTRACE:
[1] TestCaseInfoPanel::Update(lc3_test&)
[2] RunTestDialog::OnSelectTestItem(wxTreeEvent&)
[3] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[4] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[5] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[6] wxEvtHandler::TryHereOnly(wxEvent&)
[7] wxEvtHandler::ProcessEventLocally(wxEvent&)
[8] wxEvtHandler::ProcessEvent(wxEvent&)
[9] wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)
[10] wxGenericTreeCtrl::DoSelectItem(wxTreeItemId const&, bool, bool)
[11] wxGenericTreeCtrl::OnMouse(wxMouseEvent&)
[12] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[13] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[14] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[15] wxEvtHandler::TryHereOnly(wxEvent&)
[16] wxEvtHandler::ProcessEventLocally(wxEvent&)
[17] wxEvtHandler::ProcessEvent(wxEvent&)
[18] wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)
[19] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[20] g_closure_invoke
[21] g_signal_emit_valist
[22] g_signal_emit
[23] gtk_propagate_event
[24] gtk_main_do_event
[25] g_main_context_dispatch
[26] g_main_loop_run
[27] gtk_main
[28] wxGUIEventLoop::DoRun()
[29] wxEventLoopBase::Run()
[30] wxDialog::ShowModal()
[31] ComplxFrame::OnRunTests(wxCommandEvent&)
[32] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[33] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[34] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[35] wxEvtHandler::TryHereOnly(wxEvent&)
[36] wxEvtHandler::ProcessEventLocally(wxEvent&)
[37] wxEvtHandler::ProcessEvent(wxEvent&)
[38] wxWindowBase::TryAfter(wxEvent&)
[39] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[40] wxMenuBase::SendEvent(int, int)
[41] g_closure_invoke
[42] g_signal_emit_valist
[43] g_signal_emit
[44] g_main_context_dispatch
[45] g_main_loop_run
[46] gtk_main
[47] wxGUIEventLoop::DoRun()
[48] wxEventLoopBase::Run()
[49] wxAppConsoleBase::MainLoop()
[50] wxEntry(int&, wchar_t**)
[51] main
[52] __libc_start_main
[53] _start
```

**Comment by TricksterGuy** [comment] 2015-10-09 05:38
This is a duplicate of issue #31

**Closed by TricksterGuy** 2015-10-09 05:38 UTC

**Comment by lucasec** [comment] 2015-10-09 12:33
Sorry.  Based off the vague wording of #31 I assumed it was referring to the dialog not even opening, which I had never encountered.  Being more precise with the issue descriptions should cut down on duplicate reports.

**Comment by TricksterGuy** [comment] 2015-10-09 14:40
Its fine.
