### ISSUE TITLE
Console Input crash for macOS

### ISSUE THREAD

**Issue by anushkmittal** [TricksterGuy/complx#80] opened 2017-10-06 04:48 UTC
**macOS Version:** 10.12.6 (16G29)

**Complx Version:** 4.15.6

**Installation Method:** Homebrew: `https://github.com/skyman/homebrew-gt`

**Steps to Reproduce:** 1. Try clicking on the input bar in the console

**Expected Results:** Expected character appears in the input bar

**Actual Results:** Crash with `Segmentation fault: 11`

**Comment by TricksterGuy** [comment] 2017-10-06 04:51
What input bar?

**Comment by anushkmittal** [comment] 2017-10-06 04:52
The bottom bar here:

<img width="356" alt="screen shot 2017-10-06 at 12 52 04 am" src="https://user-images.githubusercontent.com/13961658/31263503-9de44786-aa30-11e7-9c1e-d318a549b210.png">

**Comment by TricksterGuy** [comment] 2017-10-06 04:59
Can you compile the program under debug settings and run through a debugger and give me a stacktrace?

You should be able to while configuring Cmake's generators, compiling the program yourself, and then running under gdb.

**Comment by anushkmittal** [comment] 2017-10-06 05:52
Sorry, I don't have any experience with C++ programming. I was able to compile DEBUG configured complx but ended up running into another error when trying to launch complx.

<img width="640" alt="screen shot 2017-10-06 at 1 48 22 am" src="https://user-images.githubusercontent.com/13961658/31264703-d03eb54c-aa38-11e7-86d2-7a74ed716326.png">

**Comment by TricksterGuy** [comment] 2017-10-06 06:40
no stacktrace then  G-A-M-E-O-V-E-R

but seriously find the TA named Cem and bug him.

I can't resolve this without a stacktrace.

**Comment by skyman** [comment] 2017-10-06 15:59
Hey Anushk,

I’m well aware of this issue, since I had it myself too - the problem only occurs on Touch Bar Macs when the Touch Bar helper tries to populate the bar with relevant emojis...

It’s not a bug with complx but with the wxWidgets / OSX interaction that was acknowledged by Apple.

The bug was fixed for inputs (still happens for read-only) in one of the updates for Sierra, and then completely fixed in High Sierra.

Please try updating the OS at least to the newest version of Sierra through the App Store, and get back to me on the homebrew-gt repository if you keep having issues.

Thanks for your report,
Cem

**Closed** 2017-10-06 16:47 UTC
